routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GroupsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/index', function () {
    return view('index');
});

Route::get('/dashboard', [DashboardController::class, 'dashboard'])->middleware(['auth'])->name('dashboard');

Route::get('/join/{group_slug}/{session_id}', [GroupsController::class, 'join'])->middleware(['auth'])->name('join');

Route::get('/join-groups', [GroupsController::class, 'join'])->middleware(['auth'])->name('join-groups');

Route::post('/store-dashboard-url', [GroupsController::class, 'storeDashboardUrl'])->middleware(['auth'])->name('store-dashboard-url');

// Route::delete('/leave-group', [DashboardController::class, 'leaveGroup'])->middleware(['auth'])->name('leave-group');

Route::resource('groups', GroupsController::class)->middleware(['auth']);

require __DIR__.'/auth.php';

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Group extends Model
{
    use HasFactory, Sluggable;

    protected $fillable = [
        'name',
        'slug',
        'type',
        'description',
        'user_id',
        'join_link',
        'board_url'
    ];

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'name',
                'onUpdate'=> false,
            ]
        ];
    }
}

app/Http/Controllers/GroupsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Validator;
use Former;
use Session;
use Auth;
use App\Models\Group;

class GroupsController extends Controller
{

    public function index()
    {
        $groups = Group::all();

        if (Auth::user()->role == 'tutor') {
            return view('groups.tutor-index', compact('groups'));
        } else {
            return view('groups.student-index', compact('groups'));
        }
    }

    public function create()
    {
        return view('groups.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'description' => 'required|max:500',
        ]);

        if ($validator->fails()) {
            Former::withErrors($validator);
            return redirect()->back()->withErrors($validator)->withInput()->withError('Please correct following errors!');
        }
        try {
            $random = \Str::random(40);
            $group = new Group;
            $group->user_id = Auth::user()->id;
            $group->name = $request->name;
            $group->description = $request->description;
            $group->save();

            $group = Group::find($group->id);
            $group->join_link = route('join', [$group->slug, $random]);
            $group->save();

            $ch = curl_init();
            $curlConfig = array(
                CURLOPT_URL            => "https://api-us.cometchat.io/v2.0/groups",
                CURLOPT_POST           => true,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_POSTFIELDS     => array(
                    'name' => $group->name,
                    'guid' => $group->slug,
                    'type' => 'public',
                    'description' => $group->description,
                    'owner' => Auth::user()->slug
                ),
                CURLOPT_HTTPHEADER => array(
                    'appId: 332521fe408663b',
                    'apiKey: a77166f434b93838baac315ce972f1e11116889a',
                )
            );
            curl_setopt_array($ch, $curlConfig);
            $result = curl_exec($ch);
            curl_close($ch);

            return redirect()->route('groups.index')->withSuccess('Group created successfully!');
        } catch (\Exception $e) {
            return redirect()->back()->withError('Something went wrong, Please try after sometime!');
        }
    }

    public function show($group_id)
    {
        try {
            $group = Group::find($group_id);

            //show old
            // $user = Auth::user();

            // $ch = curl_init();
            // $curlConfig = array(
            //     CURLOPT_URL            => "https://api-us.cometchat.io/v2.0/users/".$user->slug."/groups/".$group->slug."/members",
            //     CURLOPT_POST           => true,
            //     CURLOPT_RETURNTRANSFER => true,
            //     CURLOPT_HTTPHEADER => array(
            //         'appId: 332521fe408663b',
            //         'apiKey: a77166f434b93838baac315ce972f1e11116889a',
            //     )
            // );
            // curl_setopt_array($ch, $curlConfig);
            // $result = curl_exec($ch);
            // $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            // curl_close($ch);
            // if ($httpcode == 417) {
            //     return redirect()->back()->withError('Something went wrong, Please try after sometime!');
            //     print('You have already joined group!');
            // } else {
            //     return view('groups.show', compact('group'));
            // }
            return view('groups.show', compact('group'));
        } catch (\Exception $e) {
            return redirect()->back()->withError('Something went wrong, Please try after sometime!');
        }
    }

    public function join($group_slug, $session_id)
    {
        try {
            $group = Group::where('slug', $group_slug)->first();
            return view('groups.join', compact('group', 'session_id'));
        } catch (\Exception $e) {
            return redirect()->back()->withError('Something went wrong, Please try after sometime!');
        }
    }

    public function edit($group_id)
    {
        $group = Group::find($group_id);
        return view('groups.edit', compact('group'));
    }

    public function update(Request $request, $group_id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'description' => 'required|max:500',
        ]);

        if ($validator->fails()) {
            Former::withErrors($validator);
            return redirect()->back()->withErrors($validator)->withInput()->withError('Please correct following errors!');
        }
        try {
            $group = Group::find($group_id);
            $group->name = $request->name;
            $group->description = $request->description;
            $group->save();

            $ch = curl_init();
            $curlConfig = array(
                CURLOPT_URL            => "https://api-us.cometchat.io/v2.0/groups/" .$group->slug,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_CUSTOMREQUEST  => "PUT",
                CURLOPT_POSTFIELDS     => http_build_query(array(
                    'name' => $request->name,
                    // 'description' => $group->description,
                )),
                CURLOPT_HTTPHEADER => array(
                    'appId: 332521fe408663b',
                    'apiKey: a77166f434b93838baac315ce972f1e11116889a',
                )
            );
            curl_setopt_array($ch, $curlConfig);
            $result = curl_exec($ch);
            curl_close($ch);

            return redirect()->route('groups.index')->withSuccess('Group created successfully!');
        } catch (\Exception $e) {
            return redirect()->back()->withError('Something went wrong, Please try after sometime!');
        }
    }

    public function destroy($group_id)
    {
        try {
            $group = Group::find($group_id);
            $group->delete();

            $ch = curl_init();
            $curlConfig = array(
                CURLOPT_URL  => "https://api-us.cometchat.io/v2.0/groups/" .$group->slug,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_CUSTOMREQUEST  => "DELETE",
                CURLOPT_HTTPHEADER => array(
                    'appId: 332521fe408663b',
                    'apiKey: a77166f434b93838baac315ce972f1e11116889a',
                )
            );
            curl_setopt_array($ch, $curlConfig);
            $result = curl_exec($ch);
            curl_close($ch);

            return redirect()->route('groups.create')->withSuccess('Group created successfully!');
        } catch (\Exception $e) {
            return redirect()->back()->withError('Something went wrong, Please try after sometime!');
        }
    }

    public function storeDashboardUrl(Request $request)
    {
        try {
            $group = Group::where('slug', $request->guid)->first();
            $group->board_url = $request->board_url;
            $group->save();

            return response()->json(["success" => "Inserted successfully."], 200);
        } catch (\Exception $e) {
            return response()->json(["error" => "Something went wrong, Please try after sometime."], 422);
        }
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/groups/create.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      Create Group
    </h2>
  </x-slot>

  <div class="py-12">
    <div class="container">
      <form method="POST" action="{!! route('groups.store') !!}">
        @csrf
        <div class="form-group">
          <label for="exampleInputName">Name</label>
          <input type="text" name="name" class="form-control" id="exampleInputName" aria-describedby="textHelp" placeholder="Enter name">
           @error('name')
                  <span class="help">{{ $message }}</span>
           @enderror
        </div>
        <div class="form-group">
          <label for="exampleInputDescription">Description</label>
          <textarea name="description" class="form-control" id="exampleInputDescription"></textarea>
         @error('description')
                <span class="help">{{ $message }}</span>
         @enderror
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
</x-app-layout>

resources/views/groups/edit.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      Update Group
    </h2>
  </x-slot>

  <div class="py-12">
    <div class="container">
      <form method="POST" action="{!! route('groups.update', $group->id) !!}">
        @method('patch')
        @csrf
        <div class="form-group">
          <label for="exampleInputName">Name</label>
          <input type="text" name="name" class="form-control" id="exampleInputName" aria-describedby="textHelp" placeholder="Enter name" value="{!! $group->name !!}">
           @error('name')
                <span class="help">{{ $message }}</span>
           @enderror
        </div>
        <div class="form-group">
          <label for="exampleInputDescription">Description</label>
          <textarea name="description" class="form-control" id="exampleInputDescription">{!! $group->description !!}</textarea>
           @error('description')
                <span class="help">{{ $message }}</span>
           @enderror
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
    {{-- <form method="POST" action="{{ route('groups.destroy',$group->id) }}">
      @method('delete')
      @csrf
      <a href="{{ route('groups.destroy',$group->id) }}" class="float-right btn btn-outline-danger" onclick="event.preventDefault();
      this.closest('form').submit();">delete</a>
   </form> --}}
</div>
</x-app-layout>

resources/views/groups/join.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      {{ __('Dashboard') }}
    </h2>
  </x-slot>

  <div class="py-12">
    <div class="container">
      <div class="row">
        {{-- <div class="col-xs-6 col-md-6">
             <div class="callScreen" id="callScreen"></div>
        </div> --}}
     {{--    <div class="col-xs-6 col-md-6">
          <iframe id="white-board" src="{!! $group->board_url !!}" width="100%" height="600px" frameBorder="0" style="border: 0;"></iframe>
        </div> --}}
       {{--  <a href="https://document-embed-us.cometchat.io/p/eyJhcHBJZCI6IjMxNTAzMDkzODlhYmUyOCIsInJlY2VpdmVyIjoibWF0aHMiLCJyZWNlaXZlclR5cGUiOiJncm91cCIsInRpbWVzdGFtcCI6MTYxNzc5MjM5NiwiaWF0IjoxNjE3NzkyMzk2fQ~FnpbUGY5pTvazPKT2fB1yqTtg-zACnoWx2tfcEw2hFw" >Document</a> --}}
      {{--  <EMBED SRC="https://document-embed-us.cometchat.io/p/eyJhcHBJZCI6IjMxNTAzMDkzODlhYmUyOCIsInJlY2VpdmVyIjoibWF0aHMiLCJyZWNlaXZlclR5cGUiOiJncm91cCIsInRpbWVzdGFtcCI6MTYxNzc5MjM5NiwiaWF0IjoxNjE3NzkyMzk2fQ~FnpbUGY5pTvazPKT2fB1yqTtg-zACnoWx2tfcEw2hFw" VOLUME="50" HEIGHT="200" WIDTH="144"> --}}
        {{-- <a href="javascript:;" class="screen">Screen Share</a> --}}
        <div class="col-xs-6 col-md-4">
            <div id="cometchat"></div>
        </div>
        {{-- <a href="javascript:;" class="mute">Mute Audio</a> --}}
        {{-- 2.3.2 --}}
      </div>

    <br/>
    </div>
  </div>
@section('scripts')
  <script type="text/javascript" src="https://unpkg.com/@cometchat-pro/chat@2.3.0/CometChat.js"></script>
  <script defer src="https://widget-js.cometchat.io/v2/cometchatwidget.js"></script>
  {{-- <script type="text/javascript" src="{!! asset('js/CometChat.js') !!}"></script>
  <script src="{!! asset('/js/cometchatwidget.js') !!}"></script> --}}
  <script type="text/javascript">
    var guid = "{!! $group->slug !!}";
    var uid = "{!! Auth::user()->slug !!}";
    var authToken = "{!! Auth::user()->auth_token  !!}";
    var session_id = "{!! $session_id !!}";
    var has_dashboard_url = {!! isset($group->board_url) ? 'true' : 'false' !!};
  </script>
  <script src="{!! asset('/js/join.js') !!}"></script>
 {{--  <script type="text/javascript">
        // CometChat.callExtension("whiteboard", "POST", "v1/create", { 
        //         "receiver": guid,
        //         "receiverType": "group"
        //      }).then(response => {
        //         // Response with board_url
        //         console.log(response);
        //     }).catch(error => {
        //         // Some error occured
        //         console.log('error');
        // });
  </script> --}}
@endsection
</x-app-layout>

resources/views/groups/show-old.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      {{ __('Dashboard') }}
    </h2>
  </x-slot>

  <div class="py-12">
    <div class="container">
      <div class="row">
        <div class="col-xs-6 col-md-4">
          {{-- <img src="{!! asset('images/1.jpeg') !!}" > --}}
             <div class="callScreen" id="callScreen"></div>
        </div>
        <div class="col-xs-6 col-md-4">
          <iframe src="https://whiteboard-embed-us.cometchat.io?whiteboardid=eyJhcHBJZCI6IjMxNTAzMDkzODlhYmUyOCIsInJlY2VpdmVyIjoibWF0aHMiLCJyZWNlaXZlclR5cGUiOiJncm91cCIsInRpbWVzdGFtcCI6MTYxNzYxNDIzMiwiaWF0IjoxNjE3NjE0MjMyfQ~9Oc0WdJuB9_5vmYZ3oWQZBxnRbMS9la9lYmuH2IIOj8&accesstoken=board" width="100%" height="600px" frameBorder="0" style="border: 0;"></iframe>
        </div>
        <div class="col-xs-6 col-md-4">
            <div id="cometchat"></div>
          {{-- <img src="{!! asset('images/1.jpeg') !!}" > --}}
        </div>
      </div>

    <br/>
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <a href="javascript:;" class=" btn-sm btn-success initiate-call"> Initiate Call </a>
      </div>
      <br/>

      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <a href="javascript:;" class=" btn-sm btn-success accept-call"> Accept Call </a>
      </div>
      <br/>

       <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <a href="javascript:;" class=" btn-sm btn-success reject-call"> Reject Call </a>
      </div>

      {{-- <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <a href="{!! route('leave-group',$group->id) !!}" class="btn-sm btn-success">Leave Group</a>
      </div> --}}
    </div>
  </div>
  @section('scripts')
  <script type="text/javascript" src="https://unpkg.com/@cometchat-pro/chat@2.3.0/CometChat.js"></script>
  <script defer src="https://widget-js.cometchat.io/v2/cometchatwidget.js"></script>
  <script type="text/javascript">
    var guid = "{!! $group->slug !!}";
    var uid = "{!! Auth::user()->slug !!}";
    var authToken = "{!! Auth::user()->auth_token  !!}"
  </script>
  <script defer src="{!! asset('/js/comet.js') !!}"></script>
  <script type="text/javascript"> 

    var guid = "{!! $group->slug !!}";
    var uid = "{!! Auth::user()->slug !!}";

    // var appID = "3150309389abe28";
    // var region = "us";
    // var appSetting = new CometChat.AppSettingsBuilder().subscribePresenceForAllUsers().setRegion(region).build();
    // CometChat.init(appID, appSetting).then(
    //   () => {
    //     console.log("Initialization completed successfully");
    //   },
    //   error => {
    //     console.log("Initialization failed with error:", error);
    //   }
    //   );


    // var authToken = 'rutul-thakkar-3_161761409468baad30318e19e3455fce34145485';
    // CometChat.login(authToken).then(
    //   User => {
    //     console.log("Login successfully:", { User });

    //         // CometChat.callExtension("whiteboard", "POST", "v1/create", { 
    //         //     "receiver": guid,
    //         //     "receiverType": "group"
    //         //  }).then(response => {
    //         //     // Response with board_url
    //         //     console.log('hi');
    //         //     console.log(response);
    //         // }).catch(error => {
    //         //     // Some error occured
    //         //     console.log('error');
    //         // });

    //         // CometChat.callExtension("document", "POST", "v1/create", { 
    //         //     "receiver": "group_1617182800889",
    //         //     "receiverType": "group"
    //         // }).then(response => {
    //         //     console.log(response);
    //         // }).catch(error => {
    //         //     // Some error occured
    //         // });


    //         // var receiverID = guid;
    //         // var messageText = "Hello world!";
    //         // var receiverType = CometChat.RECEIVER_TYPE.GROUP;

    //         // var textMessage = new CometChat.TextMessage(
    //         //   receiverID,
    //         //   messageText,
    //         //   receiverType
    //         // );

    //         // CometChat.sendMessage(textMessage).then(
    //         //   message => {
    //         //     console.log("Message sent successfully:", message);
    //         //   },
    //         //   error => {
    //         //     console.log("Message sending failed with error:", error);
    //         //   }
    //         // );

    //         // var receiverID = guid;
    //         // var callType = CometChat.CALL_TYPE.VIDEO;
    //         // var receiverType = CometChat.RECEIVER_TYPE.GROUP;

    //         // var call = new CometChat.Call(receiverID, callType, receiverType);

    //         // CometChat.initiateCall(call).then(
    //         //   outGoingCall => {
    //         //     console.log("Call initiated successfully:", outGoingCall);
    //         //   // perform action on success. Like show your calling screen.
    //         // },
    //         // error => {
    //         //   console.log("Call initialization failed with exception:", error);
    //         // }
    //         // );

    //         // CometChat.acceptCall("1617621832e78f36d110a59dfbac5f0b3a2adff5aa7f91006c").then(
    //         //   call => {
    //         //     console.log("Call accepted successfully:", call);
    //         //     var sessionId = call.sessionId;
    //         //     var callType = call.type;
    //         //     var callSettings = new CometChat.CallSettingsBuilder()
    //         //     .setSessionID(sessionId)
    //         //     .enableDefaultLayout(true)
    //         //     .setIsAudioOnlyCall(callType == 'audio' ? true : false)
    //         //     .build();
    //         //     CometChat.startCall(
    //         //       callSettings,
    //         //       document.getElementById("callScreen"),
    //         //       new CometChat.OngoingCallListener({
    //         //         onUserJoined: user => {
    //         //           /* Notification received here if another user joins the call. */
    //         //           console.log("User joined call:", user);
    //         //           /* this method can be use to display message or perform any actions if someone joining the call */
    //         //         },
    //         //         onUserLeft: user => {
    //         //          // Notification received here if another user left the call. 
    //         //          console.log("User left call:", user);
    //         //          /* this method can be use to display message or perform any actions if someone leaving the call */
    //         //        },
    //         //        onUserListUpdated: userList => {
    //         //         console.log("user list:", userList);
    //         //       },
    //         //       onCallEnded: call => {
    //         //         /* Notification received here if current ongoing call is ended. */
    //         //         console.log("Call ended:", call);
    //         //         /* hiding/closing the call screen can be done here. */
    //         //       },
    //         //       onError: error => {
    //         //         console.log("Error :", error);
    //         //         /* hiding/closing the call screen can be done here. */
    //         //       }
    //         //     })
    //         //       );
    //         //   // start the call using the startCall() method
    //         // },
    //         // error => {
    //         //   console.log("Call acceptance failed with error", error);
    //         //   // handle exception
    //         // }
    //         // );

    //       },
    //       error => {
    //         console.log("Login failed with exception:", { error });
    //         // User login failed, check error and take appropriate action.
    //       }
    //       );


    window.addEventListener('DOMContentLoaded', (event) => {
      CometChatWidget.init({
        "appID": "3150309389abe28",
        "appRegion": "us",
        "authKey": "bf85ffe16dd5b207a4fe7316c1d09f7823ea5255"
      }).then(response => {
        console.log("Initialization completed successfully");
                //You can now call login function.
                CometChatWidget.login({
                  "uid": uid
                }).then(response => {
                  CometChatWidget.launch({
                    "widgetID": "0dbad388-a9e7-43e2-b8a0-51c7604d3461",
                    "target": "#cometchat",
                    "roundedCorners": "true",
                    "height": "600px",
                    "width": "600px",
                        "defaultID": guid, //default UID (user) or GUID (group) to show,
                        "defaultType": 'group' //user or group
                      });
                }, error => {
                  console.log("User login failed with error:", error);
                    //Check the reason for error and take appropriate action.
                  });
              }, error => {
                console.log("Initialization failed with error:", error);
                //Check the reason for error and take appropriate action.
              });
    });
</script>
@endsection
</x-app-layout>

resources/views/groups/show.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      Group Details
  </h2>
</x-slot>

<div class="py-12">
    <div class="container">
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr><th style="width: 90px;">Group Name</th><td>{!! $group->name !!}</td></tr>
              <tr><th style="width: 90px;">Group Description</th><td>{!! $group->description !!}</td></tr>
              <tr><th style="width: 90px;">Join Link</th><td><a href="{!! $group->join_link !!}" target="_blank">{!! $group->join_link !!} </a></td></tr>
            </tbody>
         </table>
        </div>
    </div>
</div>
</x-app-layout>

resources/views/groups/student-index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
           Groups
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="py-12">
            <div class="container">
                <div class="p-6 bg-white border-b border-gray-200">
                    <table class="table">
                       <thead>
                          <th>Name</th>
                          <th>Join Link</th>
                      </thead>
                      <tbody>
                        @foreach($groups as $group)
                        <tr>
                            <td>{!! $group->name !!}</td>
                            <td><a href="{!! $group->join_link !!}">{!! $group->join_link !!}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            </div>
        </div>

        {{-- <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <a href="{!! route('groups.show',5) !!}" class="btn-sm btn-success">Join Group</a>
        </div> --}}
    </div>
  @section('scripts')
      <script type="text/javascript" src="https://unpkg.com/@cometchat-pro/chat@2.3.0/CometChat.js"></script>
      <script defer src="https://widget-js.cometchat.io/v2/cometchatwidget.js"></script>
     {{--  <script type="text/javascript">
        $('.join').on('click', function() {
            var url = $(this).data('url');
            window.location.href = url;
        });
      </script> --}}
  @endsection
</x-app-layout>

resources/views/groups/tutor-index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
           Groups
        </h2>
    </x-slot>

    <div class="py-12">
        {{-- <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div> --}}

        <div class="py-12">
            <div class="container">
                <div class="p-6 bg-white border-b border-gray-200">
                    <a href="{!! route('groups.create') !!}" class="float-right btn btn-outline-primary">Add Group</a>
                    <table class="table">
                       <thead>
                          <th>Name</th>
                          <th>Action</th>
                      </thead>
                      <tbody>
                        @foreach($groups as $group)
                        <tr>
                            <td>{!! $group->name !!}</td>
                            <td> 
                                <a href="{!! route('groups.show',$group->id) !!}" class="btn-sm btn-success">Show Group</a>
                                <a href="{!! route('groups.edit',$group->id) !!}" class="btn-sm btn-primary">Edit Group</a>
                               {{--  <a href="javascript:;" class="join" data-url="{!! route('join',[$group->slug, $random])  !!}">{!! route('join',[$group->slug, $random]) !!}</a> --}}
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            </div>
        </div>

        {{-- <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <a href="{!! route('groups.show',5) !!}" class="btn-sm btn-success">Join Group</a>
        </div> --}}
    </div>
  @section('scripts')
      <script type="text/javascript" src="https://unpkg.com/@cometchat-pro/chat@2.3.0/CometChat.js"></script>
      <script defer src="https://widget-js.cometchat.io/v2/cometchatwidget.js"></script>
      {{-- <script type="text/javascript">
        $('.join').on('click', function() {
            var url = $(this).data('url');
            window.location.href = url;
        });
      </script> --}}
  @endsection
</x-app-layout>